### ISSUE TITLE
Module 2 exports - each export run is different

### ISSUE THREAD

**Issue by thejollygeo** [Blue-Ventures-Conservation/GEM#24]
In Module 2, upon clicking 'Start Classification' contemporary and historical maps are produced and shown.  These are sent to Tasks for the user to run an export.  However users will typically want to export twice, once to EE Assets to run Module 3, and once to their Google Drive for local storage and use outside of EE.

As it stands, users need to re-run Module 2 classification to run that second export, which means the exported classification maps to Drive are different to the first export to EE Assets.

Can a button be added to the Console following the accuracy scores, to allow users to run a second export?  The button might say something like 'Export maps again'

![image](https://github.com/user-attachments/assets/345a1010-fe0a-4147-a2c3-819f15e4b4d4)

**Comment by zibnix** [comment]
Hi Sam,

This is fixed in this commit:
https://github.com/Blue-Ventures-Conservation/GEM/commit/5847bcb0c12520310f790dc21e7c316b7494909e

If you have older assets still in GEE that you'd like to export to drive, you can always export them again as GeoTIFFs by importing them into a script (along with the ROI):

```javascript
Export.image.toDrive({
  image: myAsset,
  region: ROI,
  fileNamePrefix: 'velondriake_cont_or_hist',
  scale: 30,
  maxPixels: 1e13,
});
```

**Comment by thejollygeo** [comment]
Quick work, thanks!
