### ISSUE TITLE
Only one pixel date across pixels which are from different images

### ISSUE THREAD

**Issue by thejollygeo** [Blue-Ventures-Conservation/GEM#31]
Within a single composite, different pixels which are clearly from different images, read the same date values, e.g. in [this script](https://code.earthengine.google.com/a0d5603b6ab02fffa5f5c6a6f73fc8ff?noload=true), as explained below.  Is the pixel date calculation correct for all pixels?

The stars show the three pixels which were selected, pixels almost certainly from at least 2 different images, yet the Landsat image date is the same for all three (the Historical High Tide image is in question here, and shown in the maps):

![image](https://github.com/user-attachments/assets/cce64dca-58af-4f89-aab8-697efca0eb9d)

![image](https://github.com/user-attachments/assets/8dd594d3-d2ba-447b-b6c4-8592b58065da)

![image](https://github.com/user-attachments/assets/a61acf9f-bd65-4fdf-a41f-c6495b86fd14)

**Comment by zibnix** [comment]
This was an interesting thread to pull on!

The problem ends up being that the date bands are added after the cloud masking, so the date gets pulled from the image on top, even where it should be masked, because the date bands are not masked in the same areas as the visual bands.

The fix is to add the date bands to the imagery before masking, which is easy enough, but this also has implications for the tidal bands as well, which are added after the cloud masking. In testing, the same issue occurs there, where pixels are assigned an MNDWI value from the wrong scene, causing the quality mosaic to then pull pixels from the wrong scene when separating high and low tide.

I will move things around so that the tidal bands and the date bands are added before cloud masking. Any time a band is added to the imagery before we do the quality mosaic, we need to be sure that the bands are added before any image level masking takes place.

**Comment by zibnix** [comment]
Ok, recent commits have fixed this issue with the dates, as well as with the tidal bands and ordering for high and low tide in areas that were previously intended to be masked by the cloud mask.

In this specific region you're looking at, you won't see these same artifacts in the imagery, because (due to the tide band changes) the visual imagery selected no longer has as much cloud masked area in it and is from a different date.

**Comment by thejollygeo** [comment]
Oh cool, well that's good news!
The dates now work 👍 

As you stated these fixes change the composites generated for our MHJ work, in the areas which are masked out due to clouds.  Those artifacts in the historical high-tide have indeed gone, perhaps due to a different image being used in the east of the ROI.  However the historical low-tide image isn't so nice now (some cloud shadow, some blotchiness).  I've switched up the Historical parameters and have landed on [these beauties](https://docs.google.com/presentation/d/1Ifx7-oIB4Z6cTzXWNaU3awTwb-5AxI6ZkuhcgFrwOSo/edit#slide=id.g30a7a1c8171_0_8).

Onto Mahajamba Module 2!

**Comment by zibnix** [comment]
Looking great! Hopefully there should be more separation between high and low tide conditions in the future as well, as this change is a more accurate use of the MNDWI when selecting imagery.
