### ISSUE TITLE
Selecting ROI buffer (GEM v2)

### ISSUE THREAD

**Issue by thejollygeo** [Blue-Ventures-Conservation/GEM#36]
Using GEM v2 to map ICF site Kubu Raya, Indonesia:  took 8 mins to load the bar chart, longer than I expected, is this about right?
Some of the buffers did not load on the map due to errors (though some did);
![image](https://github.com/user-attachments/assets/8cca3fac-f267-4d2e-845f-d0367ac610f3)

FYI I chose 7.5 km buffer at 137,686.79 ha instead of 10 km buffer at 137,695.192 ha (8.4 ha higher), as the 8.4 ha is not worth retaining an extra 2.5 km of landscape across the buffer area.  The 7.5 km buffer contains 99.9939% of all known mangrove.

**Comment by zibnix** [comment]
I suspect this issue and #37 both have to do with the complexity of the coastline in this area.

The first thing I noticed was that the coastline is not getting simplified because we are using a `ee.Geometry.MultiPoint` and the simplification of a point is itself. Changing the coastline to a `ee.Geometry.LineString` allows the call to simplify to actually perform its calculations, but this results in an error:
```
Geometry.simplify: Geometry has too many edges (9180789 > 2000000).
```

This is a useful error though, as I can try to just chop up the geometry into pieces smaller than the limit, so hopefully that will be enough to get the simplification to work, and then everything downstream of that should be a simpler calculation and succeed more quickly. I'll update again when I have answers to that.

**Comment by zibnix** [comment]
This is now fixed.

**Comment by thejollygeo** [comment]
Ah interesting, Kubu Raya may be the largest and most intricate coastline we have mapped using the new coastline dataset, so this is a good test and fix for larger ROIs!

There is now a new error which probably has an easy fix:

![image](https://github.com/user-attachments/assets/dc98a9b4-75ad-43f4-b71f-2761c50a55b9)

**Comment by zibnix** [comment]
For this other error, I am not seeing this and the graph comes in correctly in both v1.4 and v2 when using the Kubu Raya roi. Be sure you are using the latest link from the READ.me and let me know if you are still seeing this.

v1.4:
https://code.earthengine.google.com/64f2b576d8cab233f4d40445c5335c15?noload=true

v2:
https://code.earthengine.google.com/39f8171a895f93c73d1ff3b12b87abdc?noload=true

**Comment by thejollygeo** [comment]
This now works, I must have been using the wrong version. Thanks

**Comment by thejollygeo** [comment]
This now works, I must have been using the wrong version. Thanks
