### ISSUE TITLE
Shapefile reading error for Coarse ROI

### ISSUE THREAD

**Issue by thejollygeo** [Blue-Ventures-Conservation/GEM#39]
The following error is shown when using GEM v2, at the start of Mod1 when GEM tries to read the coarse ROI shapefile over Inhil, Indonesia:

![image](https://github.com/user-attachments/assets/04fda2ef-d138-4357-b6f1-c72f94a5e1fb)

The shapefile has the same properties as other shapefiles that do work, could you see what's going on here?

The EE script:
https://code.earthengine.google.com/73941758a555fad250c89a031f0597a0?noload=true

The shapefile is "Inhil_coarse_ROI.shp" in:
https://drive.google.com/drive/folders/1paEvLr5IkZzv7tmO7RIvIOptp5Q3Nb6r

**Comment by thejollygeo** [comment]
Same issue occurs with GEM v1.4

**Comment by zibnix** [comment]
This should now be fixed. It was caused by some of our coastline building code assuming the intersection of your ROI with the coastline dataset would produce polygons, but for this shp the intersection included some linestrings. Now that assumption is no longer made and we still keep all the points in the intersection.
